export const usersTableColumns = {
  username: 'Username',
  fullname: 'Full Name',
  organizationRole: 'User Role',
  organization: 'Organization',
  usage: 'Usage',
  usedUtilization: 'Used Utilization',
  allocatedUtilization: 'Allocated Utilization',
  allocatedNextCycle: 'Allocated Minutes for the next billing cycle',
  billingReviewsOn: `Billing Renews on`,
  actions: 'Actions',
};

export const users = [
  {
    username: 'JSMITH',
    fullname: 'John Smith',
    organization: 'Tech Corp',
    usedUtilization: 1300,
    allocatedUtilization: 1500,
    allocatedNextCycle: 1500,
    billingReviewsOn: 12,
    organizationRole: 'Employee',
    email: 'john.smith@example.com',
  },
  {
    username: 'JDOE',
    fullname: 'Jane Doe',
    organization: 'Data Solutions',
    usedUtilization: 500,
    allocatedUtilization: 1200,
    allocatedNextCycle: 1200,
    billingReviewsOn: 23,
    organizationRole: 'CEO',
    email: 'jane.doe@example.com',
  },
  {
    username: 'MBROWN',
    fullname: 'Michael Brown',
    organization: 'Tech Corp',
    usedUtilization: 600,
    allocatedUtilization: 2000,
    allocatedNextCycle: 2000,
    billingReviewsOn: 6,
    organizationRole: 'Manager',
    email: 'michael.brown@example.com',
  },
  {
    username: 'SARAHJ',
    fullname: 'Sarah Jones',
    organization: 'Global Enterprises',
    usedUtilization: 1700,
    allocatedUtilization: 1800,
    allocatedNextCycle: 1800,
    billingReviewsOn: 14,
    organizationRole: 'Tech Lead',
    email: 'sarah.jones@example.com',
  },
  {
    username: 'DAVIDW',
    fullname: 'David Wilson',
    organization: 'Data Solutions',
    usedUtilization: 1100,
    allocatedUtilization: 1400,
    allocatedNextCycle: 1400,
    billingReviewsOn: 8,
    organizationRole: 'Employee',
    email: 'david.wilson@example.com',
  },
  {
    username: 'ETHOMAS',
    fullname: 'Emily Thomas',
    organization: 'Tech Corp',
    usedUtilization: 2000,
    allocatedUtilization: 2200,
    allocatedNextCycle: 2200,
    billingReviewsOn: 25,
    organizationRole: 'Tech Lead',
    email: 'emily.thomas@example.com',
  },
  {
    username: 'ARODRIGUEZ',
    fullname: 'Adam Rodriguez',
    organization: 'Global Enterprises',
    usedUtilization: 1350,
    allocatedUtilization: 1600,
    allocatedNextCycle: 1600,
    billingReviewsOn: 30,
    organizationRole: 'Employee',
    email: 'adam.rodriguez@example.com',
  },
  {
    username: 'SWILLIAMS',
    fullname: 'Sophia Williams',
    organization: 'Data Solutions',
    usedUtilization: 950,
    allocatedUtilization: 1300,
    allocatedNextCycle: 1300,
    billingReviewsOn: 1,
    organizationRole: 'HR',
    email: 'sophia.williams@example.com',
  },
  {
    username: 'ALEE',
    fullname: 'Alexander Lee',
    organization: 'Tech Corp',
    usedUtilization: 1600,
    allocatedUtilization: 1900,
    allocatedNextCycle: 1900,
    billingReviewsOn: 14,
    organizationRole: 'Manager',
    email: 'alexander.lee@example.com',
  },
  {
    username: 'OSMITH',
    fullname: 'Olivia Smith',
    organization: 'Global Enterprises',
    usedUtilization: 300,
    allocatedUtilization: 1750,
    allocatedNextCycle: 1750,
    billingReviewsOn: 24,
    organizationRole: 'Sales Associate',
    email: 'olivia.smith@example.com',
  },
  {
    username: 'EJACKSON',
    fullname: 'Ethan Jackson',
    organization: 'Data Solutions',
    usedUtilization: 1200,
    allocatedUtilization: 1450,
    allocatedNextCycle: 1450,
    billingReviewsOn: 9,
    organizationRole: 'Developer',
    email: 'ethan.jackson@example.com',
  },
];
